version: '3'

services:
  db:
    image: mysql
    container_name: mysql_scraper
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      TZ: America/Sao_Paulo  # Definindo o fuso horário para São Paulo
    ports:
      - "${DB_PORT}:3306"
    networks:
      - mynetwork
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

networks:
  mynetwork:
    name: mysql_network
    driver: bridge

   

  

  