version: '3'

services:
  wswolf:
    container_name: wswolf
    build:
      context: .
      dockerfile: dockerfile
      args:
        - fator_bazin=${fator_bazin}
        - meses_bazin=${meses_bazin}
        - param=${param}
    networks:
      - mysql_net
    volumes:
      - logs:/app/logs  # Volume bind para a pasta /app/logs
      - backup:/app/db/backup # Volume para o backup do MySQL
      - ./.env:/app/db/.env
    environment:
      fator_bazin: ${fator_bazin}
      param: ${param}


networks:
  mysql_net:
    name: mysql_network
    external: true   