#element_vlr_acao = '//*[@id="main-2"]/div[2]/div/div[1]/div/div[1]/div/div[1]/strong'
#element_vlm_diario = '/html/body/main/div[2]/div/div[5]/div/div/div[3]/div/div/div/strong'
#element_dy= '/html/body/main/div[2]/div/div[1]/div/div[4]/div/div[1]/strong'

element_vlr_acao = '/html/body/main/div[2]/div/div[1]/div/div[1]/div/div[1]/strong'
element_vlm_diario = '/html/body/main/div[2]/div/div[5]/div/div/div[3]/div/div/div/strong'
element_dy= '/html/body/main/div[2]/div/div[1]/div/div[4]/div/div[1]/strong'


element_pl = '/html/body/main/div[2]/div/div[8]/div[2]/div/div[1]/div/div[2]/div/div/strong'
element_pvp = '/html/body/main/div[2]/div/div[8]/div[2]/div/div[1]/div/div[4]/div/div/strong'
element_vpa = '/html/body/main/div[2]/div/div[8]/div[2]/div/div[1]/div/div[9]/div/div/strong'
element_roe = '/html/body/main/div[2]/div/div[8]/div[2]/div/div[4]/div/div[1]/div/div/strong'
element_lpa = '/html/body/main/div[2]/div/div[8]/div[2]/div/div[1]/div/div[11]/div/div/strong'
element_pebit = '/html/body/main/div[2]/div/div[8]/div[2]/div/div[1]/div/div[8]/div/div/strong'
element_dlebit = '/html/body/main/div[2]/div/div[8]/div[2]/div/div[2]/div/div[3]/div/div/strong'
element_tag_along = '/html/body/main/div[2]/div/div[5]/div/div/div[2]/div/div/div/strong'
# #element_pl= '/html/body/main/div[2]/div/div[7]/div[2]/div/div[1]/div/div[2]/div/div/strong'
# element_pvp= '/html/body/main/div[2]/div/div[7]/div[2]/div/div[1]/div/div[4]/div/div/strong'
# element_vpa= '/html/body/main/div[2]/div/div[7]/div[2]/div/div[1]/div/div[9]/div/div/strong'
# element_roe= '/html/body/main/div[2]/div/div[7]/div[2]/div/div[4]/div/div[1]/div/div/strong'
# element_lpa= '/html/body/main/div[2]/div/div[7]/div[2]/div/div[1]/div/div[11]/div/div/strong'
# element_pebit = '/html/body/main/div[2]/div/div[7]/div[2]/div/div[1]/div/div[8]/div/div/strong'