version: '3'
 
services:
  db:
    image: mysql
    container_name: mysql_scraper
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wswolf
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
volumes:
  dbdata: