version: '3'
 
services:
  db:
    image: mysql
    container_name: mysql_scrapper
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: scrapper
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
volumes:
  dbdata: