-- MySQL Script generated by MySQL Workbench
-- Fri Jul 14 17:16:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wswolf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wswolf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wswolf` DEFAULT CHARACTER SET utf8 ;
USE `wswolf` ;

-- -----------------------------------------------------
-- Table `wswolf`.`acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`acao` (
  `cod_acao` CHAR(6) NOT NULL,
  `nm_tp_acao` VARCHAR(10) NULL,
  `tmnh_acao` VARCHAR(20) NULL,
  `setor` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_acao`),
  UNIQUE INDEX `cod_acao_UNIQUE` (`cod_acao` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Lista das ações disponiveis na B3';


-- -----------------------------------------------------
-- Table `wswolf`.`coleta_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`coleta_acao` (
  `dt_coleta` DATETIME NOT NULL,
  `cod_acao` CHAR(6) NOT NULL,
  `setor` VARCHAR(10) NULL,
  `vlr_acao` DOUBLE NULL,
  `vlm_diario` DOUBLE NULL,
  `dy` DOUBLE NULL,
  `pl` DOUBLE NULL,
  `vpa` DOUBLE NULL,
  `pvp` DOUBLE NULL,
  `roe` DOUBLE NULL,
  `lpa` DOUBLE NULL,
  `pebit` DOUBLE NULL,
  `vlr_intrinseco` DOUBLE NULL,
  `bazin12` DOUBLE NULL,
  `bazin36` DOUBLE NULL,
  `bazin60` DOUBLE NULL,
  `vlr_com_margem` DOUBLE NULL,
  `score` INT NULL COMMENT 'Score baseado na analise fundamentalista que foi aplicado na ação, Graham\\Bazin',
  PRIMARY KEY (`dt_coleta`, `cod_acao`),
  INDEX `fk_coleta_acao_acoes1_idx` (`cod_acao` ASC) VISIBLE,
  CONSTRAINT `fk_coleta_acao_acoes1`
    FOREIGN KEY (`cod_acao`)
    REFERENCES `wswolf`.`acao` (`cod_acao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wswolf`.`dividendo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`dividendo` (
  `cod_dividendo` INT NOT NULL AUTO_INCREMENT,
  `dt_coleta` DATETIME NOT NULL,
  `cod_acao` CHAR(6) NOT NULL,
  `dt_comunicado` DATETIME NOT NULL,
  `dt_pagamento` DATETIME NULL,
  `tp_dividendo` VARCHAR(20) NULL COMMENT 'Armazena se o dividendo é proveniente de um Dividendo(sem IR), JCP(com IR)',
  `vlr` DOUBLE NULL COMMENT 'O valor que foi pago no dividendo',
  PRIMARY KEY (`cod_dividendo`),
  INDEX `ind_acao` (`dt_coleta` ASC, `cod_acao` ASC) VISIBLE,
  CONSTRAINT `fk_dividendo_coleta_acao1`
    FOREIGN KEY (`dt_coleta` , `cod_acao`)
    REFERENCES `wswolf`.`coleta_acao` (`dt_coleta` , `cod_acao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Armazena os dividendos pagos por cada empresa listada na B3';


-- -----------------------------------------------------
-- Table `wswolf`.`carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`carteira` (
  `cod_carteira` INT NOT NULL AUTO_INCREMENT,
  `nm_carteira` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_carteira`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wswolf`.`posicao_carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`posicao_carteira` (
  `cod_posi_carteira` INT NOT NULL,
  `cod_carteira` INT NOT NULL,
  `cod_acao` CHAR(6) NOT NULL,
  `dt_aquisicao` DATETIME NOT NULL,
  `dt_venda` DATETIME NULL,
  `ind_comprado` TINYINT NULL COMMENT 'Mostra se o ativo ainda esta na carteira',
  `vlr_aquisicao` DOUBLE NULL,
  `vlr_venda` DOUBLE NULL,
  PRIMARY KEY (`cod_posi_carteira`),
  INDEX `fk_carteira_acao1_idx` (`cod_acao` ASC) VISIBLE,
  INDEX `fk_posicao_carteira_carteira1_idx` (`cod_carteira` ASC) VISIBLE,
  CONSTRAINT `fk_carteira_acao1`
    FOREIGN KEY (`cod_acao`)
    REFERENCES `wswolf`.`acao` (`cod_acao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posicao_carteira_carteira1`
    FOREIGN KEY (`cod_carteira`)
    REFERENCES `wswolf`.`carteira` (`cod_carteira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
