-- MySQL Script generated by MySQL Workbench
-- Mon Jul 24 14:39:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wswolf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wswolf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wswolf` DEFAULT CHARACTER SET utf8mb3 ;
USE `wswolf` ;

-- -----------------------------------------------------
-- Table `wswolf`.`acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`acao` (
  `cod_acao` CHAR(6) NOT NULL,
  `nm_tp_acao` VARCHAR(10) NULL DEFAULT NULL,
  `tmnh_acao` VARCHAR(20) NULL DEFAULT NULL,
  `setor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_acao`),
  UNIQUE INDEX `cod_acao_UNIQUE` (`cod_acao` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Lista das ações disponiveis na B3';


-- -----------------------------------------------------
-- Table `wswolf`.`carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`carteira` (
  `cod_carteira` INT NOT NULL AUTO_INCREMENT,
  `nm_carteira` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_carteira`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `wswolf`.`coleta_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`coleta_acao` (
  `dt_coleta` DATETIME NOT NULL,
  `cod_acao` CHAR(6) NOT NULL,
  `setor` VARCHAR(10) NULL DEFAULT NULL,
  `vlr_acao` DOUBLE NULL DEFAULT NULL,
  `vlm_diario` DOUBLE NULL DEFAULT NULL,
  `dy` DOUBLE NULL DEFAULT NULL,
  `pl` DOUBLE NULL DEFAULT NULL,
  `vpa` DOUBLE NULL DEFAULT NULL,
  `pvp` DOUBLE NULL DEFAULT NULL,
  `roe` DOUBLE NULL DEFAULT NULL,
  `lpa` DOUBLE NULL DEFAULT NULL,
  `pebit` DOUBLE NULL DEFAULT NULL,
  `vlr_intrinseco` DOUBLE NULL DEFAULT NULL,
  `bazin12` DOUBLE NULL DEFAULT NULL,
  `bazin36` DOUBLE NULL DEFAULT NULL,
  `bazin60` DOUBLE NULL DEFAULT NULL,
  `vlr_teto_margem` DOUBLE NULL DEFAULT NULL,
  `vlr_gordon` DOUBLE NULL DEFAULT NULL COMMENT 'Score baseado na analise fundamentalista que foi aplicado na ação, Graham\\\\\\\\Bazin',
  `score` INT NULL DEFAULT NULL,
  PRIMARY KEY (`dt_coleta`, `cod_acao`),
  INDEX `fk_coleta_acao_acoes1_idx` (`cod_acao` ASC) VISIBLE,
  CONSTRAINT `fk_coleta_acao_acoes1`
    FOREIGN KEY (`cod_acao`)
    REFERENCES `wswolf`.`acao` (`cod_acao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `wswolf`.`controle_coleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`controle_coleta` (
  `dt_coleta` DATETIME NOT NULL,
  `url` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`dt_coleta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `wswolf`.`dividendo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`dividendo` (
  `cod_dividendo` INT NOT NULL AUTO_INCREMENT,
  `dt_coleta` DATETIME NOT NULL,
  `cod_acao` CHAR(6) NOT NULL,
  `dt_comunicado` DATETIME NOT NULL,
  `dt_pagamento` DATETIME NULL DEFAULT NULL,
  `tp_dividendo` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Armazena se o dividendo é proveniente de um Dividendo(sem IR), JCP(com IR)',
  `vlr` DOUBLE NULL DEFAULT NULL COMMENT 'O valor que foi pago no dividendo',
  PRIMARY KEY (`cod_dividendo`),
  INDEX `ind_acao` (`dt_coleta` ASC, `cod_acao` ASC) VISIBLE,
  CONSTRAINT `fk_dividendo_coleta_acao1`
    FOREIGN KEY (`dt_coleta` , `cod_acao`)
    REFERENCES `wswolf`.`coleta_acao` (`dt_coleta` , `cod_acao`))
ENGINE = InnoDB
AUTO_INCREMENT = 3455
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'Armazena os dividendos pagos por cada empresa listada na B3';


-- -----------------------------------------------------
-- Table `wswolf`.`posicao_carteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`posicao_carteira` (
  `cod_posi_carteira` INT NOT NULL AUTO_INCREMENT,
  `cod_carteira` INT NOT NULL,
  `cod_acao` CHAR(6) NOT NULL,
  `dt_aquisicao` DATETIME NOT NULL,
  `dt_venda` DATETIME NULL DEFAULT NULL,
  `ind_comprado` TINYINT NULL DEFAULT NULL COMMENT 'Mostra se o ativo ainda esta na carteira',
  `vlr_aquisicao` DOUBLE NULL DEFAULT NULL,
  `vlr_venda` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`cod_posi_carteira`),
  INDEX `fk_carteira_acao1_idx` (`cod_acao` ASC) VISIBLE,
  INDEX `fk_posicao_carteira_carteira1_idx` (`cod_carteira` ASC) VISIBLE,
  CONSTRAINT `fk_carteira_acao1`
    FOREIGN KEY (`cod_acao`)
    REFERENCES `wswolf`.`acao` (`cod_acao`),
  CONSTRAINT `fk_posicao_carteira_carteira1`
    FOREIGN KEY (`cod_carteira`)
    REFERENCES `wswolf`.`carteira` (`cod_carteira`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;

USE `wswolf` ;

-- -----------------------------------------------------
-- Placeholder table for view `wswolf`.`carteira_pessoal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`carteira_pessoal` (`dt_coleta` INT, `cod_acao` INT, `setor` INT, `vlr_acao` INT, `vlm_diario` INT, `dy` INT, `pl` INT, `vpa` INT, `pvp` INT, `roe` INT, `lpa` INT, `pebit` INT, `vlr_intrinseco` INT, `bazin12` INT, `bazin36` INT, `bazin60` INT, `vlr_teto_margem` INT, `vlr_gordon` INT, `score` INT);

-- -----------------------------------------------------
-- Placeholder table for view `wswolf`.`carteira_wswolf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`carteira_wswolf` (`dt_coleta` INT, `cod_acao` INT, `setor` INT, `vlr_acao` INT, `vlm_diario` INT, `dy` INT, `pl` INT, `vpa` INT, `pvp` INT, `roe` INT, `lpa` INT, `pebit` INT, `vlr_intrinseco` INT, `bazin12` INT, `bazin36` INT, `bazin60` INT, `vlr_teto_margem` INT, `vlr_gordon` INT, `score` INT);

-- -----------------------------------------------------
-- Placeholder table for view `wswolf`.`ultima_coleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wswolf`.`ultima_coleta` (`dt_coleta` INT, `cod_acao` INT, `setor` INT, `vlr_acao` INT, `vlm_diario` INT, `dy` INT, `pl` INT, `vpa` INT, `pvp` INT, `roe` INT, `lpa` INT, `pebit` INT, `vlr_intrinseco` INT, `bazin12` INT, `bazin36` INT, `bazin60` INT, `vlr_teto_margem` INT, `vlr_gordon` INT, `score` INT);

-- -----------------------------------------------------
-- View `wswolf`.`carteira_pessoal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wswolf`.`carteira_pessoal`;
USE `wswolf`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `wswolf`.`carteira_pessoal` AS select `c`.`dt_coleta` AS `dt_coleta`,`c`.`cod_acao` AS `cod_acao`,`c`.`setor` AS `setor`,`c`.`vlr_acao` AS `vlr_acao`,`c`.`vlm_diario` AS `vlm_diario`,`c`.`dy` AS `dy`,`c`.`pl` AS `pl`,`c`.`vpa` AS `vpa`,`c`.`pvp` AS `pvp`,`c`.`roe` AS `roe`,`c`.`lpa` AS `lpa`,`c`.`pebit` AS `pebit`,`c`.`vlr_intrinseco` AS `vlr_intrinseco`,`c`.`bazin12` AS `bazin12`,`c`.`bazin36` AS `bazin36`,`c`.`bazin60` AS `bazin60`,`c`.`vlr_teto_margem` AS `vlr_teto_margem`,`c`.`vlr_gordon` AS `vlr_gordon`,`c`.`score` AS `score` from (`wswolf`.`posicao_carteira` `p` join `wswolf`.`coleta_acao` `c` on(((`p`.`cod_acao` = `c`.`cod_acao`) and (`p`.`dt_aquisicao` = `c`.`dt_coleta`)))) where ((`p`.`ind_comprado` = 1) and (`p`.`cod_carteira` = 2));

-- -----------------------------------------------------
-- View `wswolf`.`carteira_wswolf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wswolf`.`carteira_wswolf`;
USE `wswolf`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `wswolf`.`carteira_wswolf` AS select `c`.`dt_coleta` AS `dt_coleta`,`c`.`cod_acao` AS `cod_acao`,`c`.`setor` AS `setor`,`c`.`vlr_acao` AS `vlr_acao`,`c`.`vlm_diario` AS `vlm_diario`,`c`.`dy` AS `dy`,`c`.`pl` AS `pl`,`c`.`vpa` AS `vpa`,`c`.`pvp` AS `pvp`,`c`.`roe` AS `roe`,`c`.`lpa` AS `lpa`,`c`.`pebit` AS `pebit`,`c`.`vlr_intrinseco` AS `vlr_intrinseco`,`c`.`bazin12` AS `bazin12`,`c`.`bazin36` AS `bazin36`,`c`.`bazin60` AS `bazin60`,`c`.`vlr_teto_margem` AS `vlr_teto_margem`,`c`.`vlr_gordon` AS `vlr_gordon`,`c`.`score` AS `score` from (`wswolf`.`posicao_carteira` `p` join `wswolf`.`coleta_acao` `c` on(((`p`.`cod_acao` = `c`.`cod_acao`) and (`p`.`dt_aquisicao` = `c`.`dt_coleta`)))) where ((`p`.`ind_comprado` = 1) and (`p`.`cod_carteira` = 1));

-- -----------------------------------------------------
-- View `wswolf`.`ultima_coleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wswolf`.`ultima_coleta`;
USE `wswolf`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `wswolf`.`ultima_coleta` AS select `wswolf`.`coleta_acao`.`dt_coleta` AS `dt_coleta`,`wswolf`.`coleta_acao`.`cod_acao` AS `cod_acao`,`wswolf`.`coleta_acao`.`setor` AS `setor`,`wswolf`.`coleta_acao`.`vlr_acao` AS `vlr_acao`,`wswolf`.`coleta_acao`.`vlm_diario` AS `vlm_diario`,`wswolf`.`coleta_acao`.`dy` AS `dy`,`wswolf`.`coleta_acao`.`pl` AS `pl`,`wswolf`.`coleta_acao`.`vpa` AS `vpa`,`wswolf`.`coleta_acao`.`pvp` AS `pvp`,`wswolf`.`coleta_acao`.`roe` AS `roe`,`wswolf`.`coleta_acao`.`lpa` AS `lpa`,`wswolf`.`coleta_acao`.`pebit` AS `pebit`,`wswolf`.`coleta_acao`.`vlr_intrinseco` AS `vlr_intrinseco`,`wswolf`.`coleta_acao`.`bazin12` AS `bazin12`,`wswolf`.`coleta_acao`.`bazin36` AS `bazin36`,`wswolf`.`coleta_acao`.`bazin60` AS `bazin60`,`wswolf`.`coleta_acao`.`vlr_teto_margem` AS `vlr_teto_margem`,`wswolf`.`coleta_acao`.`vlr_gordon` AS `vlr_gordon`,`wswolf`.`coleta_acao`.`score` AS `score` from `wswolf`.`coleta_acao` where `wswolf`.`coleta_acao`.`dt_coleta` in (select max(`wswolf`.`coleta_acao`.`dt_coleta`) from `wswolf`.`coleta_acao`);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
